### ISSUE TITLE
How to render DirectShow in swapchainpanel?

### ISSUE THREAD

**Issue by sudongg** [KlearTouch/KlearTouch.MediaPlayer#4]
hi，
I used EVR Presenter to get a buffer pointer. In WPF, I used the SetBackBuffer of d3dimage to render images. What do I do in winui?

**Comment by sudongg** [comment]
Buffer pointer is an IDirect3DSurface9. I need to present IDirect3DSurface9 in SwapChainPanel.

**Comment by PierreHenriKT** [comment]
Hi,

Sorry, I don't have any experience with DirectShow/Direct3D9. I also did a quick search, but I don't see any obvious answer.

My understanding is that [SwapChainPanel works with IDXGISwapChain](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.swapchainpanel?view=winui-3.0), and [DXGI was introduced in Direct3D 10](https://en.wikipedia.org/wiki/DirectX_Graphics_Infrastructure). So, it is likely that you can't use it directly with `IDirect3DSurface9`.

The alternative that I wonder if it could work is if you could copy that D3D9 surface in memory, then put it in a D3D11 surface to render it in the `SwapChainPanel`. But even then, it might be really slow.

**Comment by sudongg** [comment]
I have found a way to render IDirect3DSurface9 to d3d11, but the effect is not very satisfactory. I may have to modify the C + + code to avoid the overhead of copying memory.
