### ISSUE TITLE
Is it possible to make this work for WPF?

### ISSUE THREAD

**Issue by geocine** [KlearTouch/KlearTouch.MediaPlayer#5]
Right now I am using the `MediaPlayerElement` from UWP through XAML Islands to display video from a `MediaCapture` `MediaFrameSource`.  Using XAML islands has a number of issues. If Its possible to make this work directly on WPF, that would be great.

**Comment by PierreHenriKT** [comment]
It will require XAML Islands for WinUI 3 which is a [planned feature](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/9-xaml-islands-use-winui-3-from-wpf-or-winforms).

There are many requests for that feature on the Windows repos, like this one: https://github.com/microsoft/microsoft-ui-xaml/issues/7104

**Comment by geocine** [comment]
XAML Islands have the airspace issue which I want to avoid so if its possible to use without going that route, that would be great.

**Comment by PierreHenriKT** [comment]
Sorry, I don't see any alternative.
